### ISSUE TITLE
Connection Error occurred while trying to post data

### ISSUE THREAD

**Issue by Quintenplaizier** [cyberjunky/RTL-SDR-P2000Receiver-HA#18]
Dear,

It is almost working, but..  i get the following error and i can't figure it out what the problem is..
Can you try to help me??

The base URL in the config is the default setting, and it also resolves en reply to a ping from the Pi.

Posting to Home Assistant
Connection Error occurred while trying to post data, check baseurl in config.ini:
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Kind regards
Quinten

**Comment by cyberjunky** [comment]
Is the token correct? Try with the IP address?

**Comment by Quintenplaizier** [comment]
With the IP i got the same error an i tried a new token but i got the same result.

Quinten

**Comment by Quintenplaizier** [comment]
It is working!!
I had to use my external base URL with SSL.

Thanx
Quinten
