### ISSUE TITLE
not posting to HA

### ISSUE THREAD

**Issue by firefigther0575** [cyberjunky/RTL-SDR-P2000Receiver-HA#21]
Dear Ron,
currently im testing de receiver i do have output but not posting to ha,
after every line that it receives i get the text ignord.
can you help me

**Comment by Dinges28** [comment]
Please check what is in ignore_text.txt

**Comment by firefigther0575** [comment]
i did and there is nothing in it...

**Comment by Dinges28** [comment]
Did you try to enable debug in the config?

**Comment by firefigther0575** [comment]
Yes id did, thats how i saw it.

it loads everything.
Loading configuration from 'config.ini'
Loading data from 'db_capcodes.txt'
87860 records loaded
Loading data from 'db_plaatsnamen.txt'
2510 records loaded
Loading data from 'db_pltsnmn.txt'
2505 records loaded
Loading data from 'ignore_capcodes.txt'
Loading data from 'ignore_text.txt'
Loading data from 'match_text.txt'
Loading data from 'match_capcodes.txt'

**Comment by Dinges28** [comment]
Try renaming the ignore and match files

**Comment by firefigther0575** [comment]
Checking if required software is installed
rtl_fm is found
multimon-ng is found
Loading configuration from 'config.ini'
Loading data from 'db_capcodes.txt'
87860 records loaded
Loading data from 'db_plaatsnamen.txt'
2510 records loaded
Loading data from 'db_pltsnmn.txt'
2505 records loaded
Loading data from 'ignore_capcodes.txt'
1 records loaded
Loading data from 'ignore_text.txt'
0 records loaded
Loading data from 'match_text.txt'
0 records loaded
Loading data from 'match_capcodes.txt'
0 records loaded
RTL-SDR process started with: rtl_fm -f 169.65M -M fm -s 22050 | multimon-ng -a FLEX -t raw -
Post thread started
Found 1 device(s):
multimon-ng 1.1.8
  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
  (C) 2012-2019 by Elias Oenal
Available demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPE
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Detached kernel driver
Tuner gain set to automatic.
Tuned to 169903575 Hz.
Oversampling input by: 46x.
Oversampling output by: 1x.
Buffer size: 8.08ms
Exact sample rate is: 1014300.020041 Hz
Sampling at 1014300 S/s.
Output at 22050 Hz.

**Comment by firefigther0575** [comment]
just a few messages to let you see whats happening

FLEX|2022-01-06 09:15:42|1600/2/K/A|04.000|002029568 001503902 001500199|ALN|P 1 BDH-15 HV Christiaan de Wetstraat 's-Gravenhage 159662
Using message stripping to find address
City found: Grave
City found: 's-Gravenhage
Message 'P 1 BDH-15 HV Christiaan de Wetstraat 's-Gravenhage 159662' ignored (matched ignore_text)
FLEX|2022-01-06 09:15:52|1600/2/K/A|04.005|001420057|ALN|B2 AMBU 17202 Rietaak 2924TG Krimpen aan den IJssel KRIMIJ bon 2559
Message 'B2 AMBU 17202 Rietaak 2924TG Krimpen aan den IJssel  bon 2559' ignored (matched ignore_text)
FLEX|2022-01-06 09:16:05|1600/2/K/A|04.012|002029568 000120999 000120103|ALN|A1 13103 Kolfschotenstraat 1104 Amsterdam 1682
Using message stripping to find address
City found: Amsterdam
Message 'A1 13103 Kolfschotenstraat 1104 Amsterdam 1682' ignored (matched ignore_text)

**Comment by cyberjunky** [comment]
@firefigther0575  is there a space character in ignore file perhaps?

**Comment by firefigther0575** [comment]
wil have a look

**Comment by Dinges28** [comment]
and otherwise rename the ignore_text.txt, so it will be completely ignored

**Comment by firefigther0575** [comment]
@ron no blank spacing, @dinges i did that then it still says matched ignore text

**Comment by Dinges28** [comment]
does it also say "Loading data from 'ignore_text.txt'"

**Comment by firefigther0575** [comment]
yes it does and 0 loaded it says

**Comment by firefigther0575** [comment]
Loading configuration from 'config.ini'
Loading data from 'db_capcodes.txt'
87860 records loaded
Loading data from 'db_plaatsnamen.txt'
2510 records loaded
Loading data from 'db_pltsnmn.txt'
2505 records loaded
Loading data from 'ignore_capcodes.txt'
1 records loaded
Loading data from 'ignore_text.txt'
0 records loaded
Loading data from 'match_text.txt'
0 records loaded
Loading data from 'match_capcodes.txt'
0 records loaded

**Comment by firefigther0575** [comment]
looks like everything in ' ' is ignored

**Comment by cyberjunky** [comment]
Whats in ignore_capcodes.txt?

**Comment by firefigther0575** [comment]
leaved that as is.

# Messages with one or more of these capcodes (9 chars long) will be ignored.
# capcode[,description]
123456789,TEST GROUP

**Comment by Dinges28** [comment]
If you rename the ignore_text.txt, it should come with this log:
```
Loading data from 'ignore_text.txt'
Could not open/read file: ignore_text.txt
```
If you rename it, and it still CAN find the file when starting the script... you probably are changing and troubleshooting the wrong files....

**Comment by firefigther0575** [comment]
Loading data from 'ignore_text.txt'
Could not open/read file: ignore_text.txt

and still it getting the same message
looking into the directory if i can find another ignore text file

**Comment by firefigther0575** [comment]
did not find it

**Comment by firefigther0575** [comment]
with a clean install on a pi with new sd i got the same problem

**Comment by leejoow** [comment]
I had the same problem. It seems it only works if you **do** have a ignore file with **at least one entry** in it. No file or a files with all commented out rows gave me the same error.

**Comment by firefigther0575** [comment]
lets try it, nothing to lose

**Comment by cyberjunky** [comment]
Yeah that could be (and is a bug ofcourse) will have some time tomorrow to fix and enhance it... just put *test* *TEST* etc in it each in new line thos msgs are not useful ;-)

**Comment by firefigther0575** [comment]
i will give it a minute to test it and will let u know!

**Comment by cyberjunky** [comment]
I mean ```*test*``` and ```*TEST*```

**Comment by firefigther0575** [comment]
we have succes!!!!

**Comment by firefigther0575** [comment]
thanks For the Help gentlemen.
