### ISSUE TITLE
How to add sensor the HA

### ISSUE THREAD

**Issue by leejoow** [cyberjunky/RTL-SDR-P2000Receiver-HA#22]
I cannot find a way to create the needed sensor in HA... Could you please add this in the guide? Just a very simple YAML example would be fine :)

**Comment by Dinges28** [comment]
You do not need to. 


As soon as the sdr sends the message, the sensor will be created in HASS

**Comment by leejoow** [comment]
Indeed, totally overlooked that one. Thanks!
