### ISSUE TITLE
ignored even when capcode is in match_capcodes.txt

### ISSUE THREAD

**Issue by aavosnl** [cyberjunky/RTL-SDR-P2000Receiver-HA#24]
message not going to homeassistant even when de capcode is in the match_capcodes.txt 

is there something that i'm doing wrong? 

![p2000fout1](https://user-images.githubusercontent.com/24371158/149629868-44d213cc-7a93-4fc9-b418-57fdaba0366a.png)

![p2000fout2](https://user-images.githubusercontent.com/24371158/149629871-790f84db-9d29-4d23-b082-c90f693412ee.png)

**Comment by Dinges28** [comment]
Does it work when you do **not** configure "match_capcodes"?

**Comment by aavosnl** [comment]
yes than everything is going to home assistan

![p20003](https://user-images.githubusercontent.com/24371158/149634767-0730b740-87f3-404c-b508-6c8b88b65c99.png)
t

**Comment by Dinges28** [comment]
Try changing line 522 from:
```capcode not in self.matchcapcodes```
to:
```capcode in self.matchcapcodes```

**Comment by aavosnl** [comment]
trying that. at that point everything is send to home assistant  except the capcodes that are inside match_capcodes.txt that is not posted to homeassistant

**Comment by Dinges28** [comment]
Maybe @cyberjunky  knows better where this goes wrong. 
Tried the above.. and at first glance it looked like it was working. Not having time to search deeper at the moment.

**Comment by cyberjunky** [comment]
I'm looking into it...

**Comment by cyberjunky** [comment]
Can you try the latest code and let me know, I added better logging and changed the logic.

**Comment by aavosnl** [comment]
Trying the latest code it look fine right now. Leaving it on for today to watch for errors.

**Comment by aavosnl** [comment]
running for couple of hours now. used different capcodes settings .  Looks that the filters are working great now. 
Thanks for the change @cyberjunky
