### ISSUE TITLE
I was missing dependency GeoPy 

### ISSUE THREAD

**Issue by cris1** [cyberjunky/RTL-SDR-P2000Receiver-HA#35]
ModuleNotFoundError: No module named 'geopy'

Solved with : 
```
pip install geopy
```

( OS : Linux srv-linux-11 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1)

**Comment by cyberjunky** [comment]
Added to instructions

**Comment by cris1** [comment]
Thanks :)
