### ISSUE TITLE
Feature request: post to mysql DB

### ISSUE THREAD

**Issue by svptje** [cyberjunky/RTL-SDR-P2000Receiver-HA#38]
Not an issue but a feature request.
Is it possible add the possibility to post p2000 results to a mysql server? So we can create the possibility to have an alternatieve rss feed for one of your other projects HA p2000.

Thanks!

**Comment by Dinges28** [comment]
In my opinion, this is not in scope of this project. It is to provide standalone p2000 messages to home assistant or mqtt...
Speaking of that... I previously found a project that saves mqtt data to an mysql database...
possibly that is a "out-of-the-box" solution for you?

https://nl.farnell.com/how-to-save-mqtt-messages-to-mysql-database

**Comment by cyberjunky** [comment]
There are other script who do this, and have a web page to retrieve them, cannot find them back though, but yeah this is purely for HA integration.
