### ISSUE TITLE
sdr isssues

### ISSUE THREAD

**Issue by firefigther0575** [cyberjunky/RTL-SDR-P2000Receiver-HA#40]
maybe a solution instead of a issue

i had some different sdr related issues.
after some fiddeling en trying .
i was having some driver troubles so i used the next code.

sudo nano /etc/modprobe.d/raspi-blacklist.conf

blacklist dvb_usb_rtl28xxu
blacklist rtl2832
blacklist rtl2830

**Comment by cyberjunky** [comment]
Thanks, I added it to the readme.
BTW I'm trying to create a home-assistant add-on for this, so we can just plug the dongle in the HA server.
Still lot of work to do though...

**Comment by firefigther0575** [comment]
> Thanks, I added it to the readme. BTW I'm trying to create a home-assistant add-on for this, so we can just plug the dongle in the HA server. Still lot of work to do though...

o that sound great! 
but.... can i use 2 sdr decoders at the same time...

i'm using a redundant system
when 1 dies... other takes over..

**Comment by firefigther0575** [comment]
when ready i would like to test it!!

**Comment by cyberjunky** [comment]
Still busy with the basic image, then the options/configurations, will let you know..
Now you have two dongles in one system? How does the takeover works? What did you code/install for that?

**Comment by firefigther0575** [comment]
i use 2 different pi3, then let it post to HA....with node red to tts. with small different name changes like * or .
with Nodered i monitor the ouput when nothing is coming of sdr 1 it looks at sdr 2 when that haves a ouput it post it to tts.
