### ISSUE TITLE
A little issue 

### ISSUE THREAD

**Issue by firefigther0575** [cyberjunky/RTL-SDR-P2000Receiver-HA#52]
i installed all code for a friend. 
but after a reboot or something it wont auto restart it
RPI 4

**Comment by cyberjunky** [comment]
Set loglevel to debug and check log tab of add-on?

**Comment by firefigther0575** [comment]
i had a log for 16 days, it shuts down whenever it wants and nothing is visible in the logs. i am leaning towards a network issue.

**Comment by cyberjunky** [comment]
Having a debug log for 16 days may even be a reason to give trouble... also check the supervisor logs... (via menu top right)

**Comment by firefigther0575** [comment]
this is not with the add on. after the issue i set it to debug.
